# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_axi_dma_0_0/Encoding_System_axi_dma_0_0.xci
# IP: The module: 'Encoding_System_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_axi_dma_0_0/Encoding_System_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Encoding_System_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_axi_dma_0_0/Encoding_System_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Encoding_System_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_axi_dma_0_0/Encoding_System_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Encoding_System_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_axi_dma_0_0/Encoding_System_axi_dma_0_0.xci
# IP: The module: 'Encoding_System_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_axi_dma_0_0/Encoding_System_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Encoding_System_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_axi_dma_0_0/Encoding_System_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Encoding_System_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_axi_dma_0_0/Encoding_System_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Encoding_System_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
