# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/Encoding_System_system_ila_0_0.xci
# IP: The module: 'Encoding_System_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/bd_0/bd_80b2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_80b2 || ORIG_REF_NAME==bd_80b2} -quiet] -quiet

# IP: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/bd_0/ip/ip_0/bd_80b2_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_80b2_ila_lib_0 || ORIG_REF_NAME==bd_80b2_ila_lib_0} -quiet] -quiet

# IP: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/bd_0/ip/ip_1/bd_80b2_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_80b2_g_inst_0 || ORIG_REF_NAME==bd_80b2_g_inst_0} -quiet] -quiet

# XDC: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_80b2_ila_lib_0 || ORIG_REF_NAME==bd_80b2_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_80b2_ila_lib_0 || ORIG_REF_NAME==bd_80b2_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/bd_0/ip/ip_0/bd_80b2_ila_lib_0_ooc.xdc

# XDC: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/bd_0/bd_80b2_ooc.xdc

# XDC: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/Encoding_System_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Encoding_System_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/Encoding_System_system_ila_0_0.xci
# IP: The module: 'Encoding_System_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/bd_0/bd_80b2.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_80b2 || ORIG_REF_NAME==bd_80b2} -quiet] -quiet

# IP: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/bd_0/ip/ip_0/bd_80b2_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_80b2_ila_lib_0 || ORIG_REF_NAME==bd_80b2_ila_lib_0} -quiet] -quiet

# IP: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/bd_0/ip/ip_1/bd_80b2_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_80b2_g_inst_0 || ORIG_REF_NAME==bd_80b2_g_inst_0} -quiet] -quiet

# XDC: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_80b2_ila_lib_0 || ORIG_REF_NAME==bd_80b2_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_80b2_ila_lib_0 || ORIG_REF_NAME==bd_80b2_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/bd_0/ip/ip_0/bd_80b2_ila_lib_0_ooc.xdc

# XDC: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/bd_0/bd_80b2_ooc.xdc

# XDC: d:/ASIC2/GitHub/Spike_Encoding_System/Spike_Encoding_System/Spike_Encoding_System.srcs/sources_1/bd/Encoding_System/ip/Encoding_System_system_ila_0_0/Encoding_System_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Encoding_System_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
